In [3]:
# to install numpy in system from jupyter notebook
!pip install numpy

In [1]:
import numpy as np
print(np.__version__)   

2.4.1


In [2]:
# Create 1 D array using numpy
arr = np.array([1,2,3,4,5]) # no no-arg method available 
print(arr)
print(type(arr)) # <class 'numpy.ndarray'>
print(arr.shape) # shape of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
# Converting 1D array to 2D array
arr1 = np.array([1,2,3,4,5])
# reshape() does NOT modify the original array - it returns a new array (or view). You're not storing the result!
arr4 = arr1.reshape(1,5) # 1 row 5 columns 
print(arr1)
print(arr1.shape)
print(type(arr1))

print(arr4)
print(arr4.shape)
print(type(arr4))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
[[1 2 3 4 5]]
(1, 5)
<class 'numpy.ndarray'>


Why This Design?
NumPy's reshape() returns a view of the original data (when possible), allowing you to:

Keep the original array unchanged
Create multiple views with different shapes from the same data

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
# arange() function creates an array of evenly spaced values. It works similar to Python's range().
arr3 = np.arange(0,10,2) # np.arange(start, stop, step)
print(arr3)
arr4 = arr3.reshape(1,5)
print(arr4)
print(arr4.shape)

[0 2 4 6 8]
[[0 2 4 6 8]]
(1, 5)


In [6]:
np.ones((3,3)) # Creates a 3×3 array filled with 1.0 (ones):

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Identity matrix
np.eye(3) # all the diagonal elements are 1 and rest are 0


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# Random matrix
print(np.random.rand(3,3)) # random values between 0 and 1

# Random matrix with integers
print(np.random.randint(0,10, (3,3))) # random values between 0 and 10

# Random matrix with float values
print(np.random.randn(3,3)) # random values between -1 and 1

[[0.48147573 0.54138371 0.59999736]
 [0.61085255 0.63834071 0.09331409]
 [0.05267604 0.52678663 0.66547673]]
[[3 3 6]
 [7 7 8]
 [3 3 4]]
[[-1.07284333  1.16739459 -0.32307418]
 [ 0.27389491  1.02800275 -0.83235392]
 [-0.73560997 -0.69279411  1.14856689]]


In [ ]:
# Arributes of array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array\n',arr)
print('Shape of array',arr.shape)
print('Data type of array',arr.dtype)
print('Number of diamnetions', arr.ndim)
print('Size of array', arr.size)
print('Array of type', type(arr))
print('Item size in bytes', arr.itemsize)

Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of array (3, 3)
Data type of array int64
Number of diamnetions 2
Size of array 9
Array of type <class 'numpy.ndarray'>
Item size in bytes 8


In [12]:
### Numpy Vectorization Operation
arr5 = np.array([1,2,3,4,5])
arr6 = np.array([6,7,8,9,10])

# Elementwise addition
print(arr5 + arr6)

# Elementwise multiplication
print(arr5 * arr6)

# Elementwise division
print(arr5 / arr6)

# Elementwise subtraction
print(arr5 - arr6)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]


In [18]:
# Universal function 
arr7 = np.array([1,2,3])

# Square root
print(np.sqrt(arr7))

# Exponential
print(np.exp(arr7))

# sine
print(np.sin(arr7))

# cosine
print(np.cos(arr7))

# log
print(np.log(arr7))

# log10
print(np.log10(arr7))

# log2
print(np.log2(arr7))

# log1p
print(np.log1p(arr7))

# logaddexp
print(np.logaddexp(arr7, arr7))

# logaddexp2
print(np.logaddexp2(arr7, arr7))



[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[0.69314718 1.09861229 1.38629436]
[1.69314718 2.69314718 3.69314718]
[2. 3. 4.]


In [23]:
# Slicing & Indexing Operation

arr8 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr8)
print("First Sub Array\n",arr8[0])
print("First Element of First Sub Array\n",arr8[0][0])

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First Sub Array
 [1 2 3]
First Element of First Sub Array
 1


In [25]:
arr8[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [39]:
print(arr8[1:,1:])

[[5 6]
 [8 9]]


In [42]:
# Statical concept -- Normalization

data = np.array([1,2,3,4,5])

# Calculate mean and standard diviation 
mean = np.mean(data)
std = np.std(data)

print(mean)
print(std)

normalized_data = (data - np.mean(data)) / np.std(data)
print(normalized_data)

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
data = [1,2,3,4,5,6,7,8,9,10]

# Mean
mean = sum(data)/len(data)
print(mean)

print(np.mean(data))

# Median
median = np.median(data)
print(median)

# Standard Deviation
std = np.std(data)
print(std)

# Variance
var = np.var(data)
print(var)


5.5
5.5
5.5
2.8722813232690143
8.25


In [51]:
# Logical Operation

data = np.array([1,2,3,4,5])
data2 = np.array([5,4,3,2,1])

print(data > 5)

print(data[ (data < 8) & (data > 5) ])

print(np.logical_and(data,data2))
print(np.logical_or(data,data2))
print(np.logical_not(data))

[False False False False False]
[]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
